# fly.toml app configuration file generated for shader-llm-api on 2025-02-02T17:29:15+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'shader-llm-api'
primary_region = 'sin'

[build]
  dockerfile = 'Dockerfile'

[env]
  PHX_HOST = 'shader-llm-api.fly.dev'
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
